import {defineType,defineField,defineArrayMember,type FieldDefinition} from 'sanity';
import {FiFileText,FiMail,FiImage} from 'react-icons/fi';
import defaults from '../src/content/defaults.json';
const labels:Record<string,string>={stage:'Etapa del proyecto',projectTypes:'Tipos de proyecto',stageLabel:'Etiqueta de etapa',stages:'Etapas del proyecto',mailHint:'Ayuda para el envío por correo',mailStatus:'Mensaje al abrir el correo',brand:'Nombre de marca',logo:'Logotipo',nav:'Navegación',contactLabel:'Botón de contacto',hero:'Portada',about:'Acerca de mí',processTitle:'Título del proceso',steps:'Pasos del proceso',servicesTitle:'Título de servicios',serviceCta:'Enlace de cotización',services:'Servicios',projectsTitle:'Título de proyectos',projectCta:'Enlace de proyecto',projects:'Proyectos',contact:'Formulario de contacto',footer:'Pie de página',socials:'Redes sociales',privacy:'Privacidad',seo:'SEO',appearance:'Colores',sections:'Orden y visibilidad de secciones',title:'Título',text:'Texto',description:'Descripción',subtitle:'Subtítulo',image:'Imagen',label:'Etiqueta',href:'Destino',primary:'Botón principal',secondary:'Botón secundario',eyebrow:'Etiqueta superior',stats:'Áreas de desarrollo',badge:'Distintivo',email:'Correo',phone:'Teléfono',copyright:'Copyright',accent:'Color de acento',surface:'Color de tarjetas',timelines:'Plazos disponibles',nameLabel:'Etiqueta de nombre',phoneLabel:'Etiqueta de WhatsApp',emailLabel:'Etiqueta de correo',serviceLabel:'Etiqueta de servicio',timelineLabel:'Etiqueta de plazo',messageLabel:'Etiqueta del mensaje',submitLabel:'Botón de envío',privacyLabel:'Texto de privacidad',marketingLabel:'Consentimiento comercial',successMessage:'Mensaje de éxito',errorMessage:'Mensaje de error',pendingLabel:'Texto mientras se envía',claimsLabel:'Texto del libro de reclamaciones',claimsUrl:'URL del libro de reclamaciones'};
const photo=defineType({name:'photo',title:'Imagen WebP',type:'image',icon:FiImage,options:{hotspot:true,accept:'image/webp'},fields:[defineField({name:'alt',title:'Texto alternativo',type:'string',validation:r=>r.required()})],validation:r=>r.custom(value=>!value?.asset?true: String(value.asset._ref).endsWith('-webp')||'Convierte la imagen a WebP antes de subirla.')});
function field(name:string,value:unknown):FieldDefinition {
 const title=labels[name]||name;
 if(['marketingLabel','timelineLabel','timelines'].includes(name))return defineField({name,title,type:name==='timelines'?'array':'string',...(name==='timelines'?{of:[defineArrayMember({type:'string'})]}:{}),readOnly:true,hidden:true,deprecated:{reason:'Campo anterior; ya no se muestra en el formulario.'}});

 if(name==='logo'||name==='image')return defineField({name,title,type:'photo'});
 if(name==='sections')return defineField({name,title,type:'array',of:[defineArrayMember({type:'string'})],options:{list:[{title:'Acerca de mí',value:'acerca'},{title:'Proceso',value:'proceso'},{title:'Servicios',value:'servicios'},{title:'Proyectos',value:'proyectos'},{title:'Contacto',value:'contacto'}]},validation:r=>r.unique()});
 if(name==='socials')return defineField({name,title,type:'array',of:[defineArrayMember({type:'object',icon:FiFileText,fields:[defineField({name:'platform',title:'Red social',type:'string',options:{list:['instagram','facebook','linkedin','whatsapp','github','tiktok']},validation:r=>r.required()}),defineField({name:'url',title:'URL del perfil',type:'url',validation:r=>r.required().uri({scheme:['https']})})],preview:{select:{title:'platform',subtitle:'url'}}})]});
 if(name==='projects')return defineField({name,title,type:'array',of:[defineArrayMember({type:'object',icon:FiFileText,fields:[field('title',''),field('category',''),field('description',''),field('image',null),defineField({name:'url',title:'URL del proyecto',type:'url',validation:r=>r.uri({scheme:['https']})}),defineField({name:'testimonial',title:'Testimonio real (opcional)',type:'text'}),defineField({name:'author',title:'Autor del testimonio',type:'string'}),defineField({name:'rating',title:'Valoración',type:'number',validation:r=>r.min(1).max(5).integer()})]})]});
 if(Array.isArray(value))return defineField({name,title,type:'array',of:[typeof value[0]==='string'?defineArrayMember({type:'string'}):defineArrayMember({type:'object',icon:FiFileText,fields:Object.entries(value[0]||{}).filter(([k])=>!k.startsWith('_')).map(([k,v])=>field(k,v))})]});
 if(value&&typeof value==='object')return defineField({name,title,type:'object',icon:FiFileText,fields:Object.entries(value).map(([k,v])=>field(k,v))});
 if(name==='icon')return defineField({name,title:'Icono',type:'string',options:{list:['landing','web','shop','code','app','systems']}});
 if(name==='accent'||name==='surface')return defineField({name,title,type:'string',validation:r=>r.required().regex(/^#[0-9a-fA-F]{6}$/, {name:'color hexadecimal #RRGGBB'})});
 if(name==='claimsUrl')return defineField({name,title,type:'url',validation:r=>r.uri({scheme:['https']})});
 if(name==='href')return defineField({name,title,type:'string',validation:r=>r.required().custom(v=>/^#[a-z][a-z0-9-]*$|^https:\/\//i.test(v||'')||'Usa un ancla (#servicios) o una URL https.')});
 const multiline=['text','description','title','subtitle'].includes(name);
 return defineField({name,title,type:multiline?'text':'string',...(multiline?{rows:3}:{}),...(name==='email'?{validation:(r)=>r.required().email()}:{})});
}
export const landingPage=defineType({name:'landingPage',title:'Landing de José Pereda',type:'document',icon:FiFileText,fields:Object.entries(defaults).filter(([k])=>!k.startsWith('_')).map(([k,v])=>field(k,v)),preview:{prepare:()=>({title:'Landing de José Pereda'})}});
export const inquiry=defineType({name:'inquiry',title:'Solicitudes de proyectos',type:'document',icon:FiMail,fields:[...['name','phone','email','service','stage','timeline','message','privacyText'].map(name=>defineField({name,title:labels[name]||name,type:name==='message'||name==='privacyText'?'text':'string',readOnly:true})),defineField({name:'createdAt',title:'Fecha',type:'datetime',readOnly:true}),defineField({name:'privacy',title:'Privacidad aceptada',type:'boolean',readOnly:true}),defineField({name:'marketing',title:'Consentimiento comercial anterior',type:'boolean',readOnly:true,hidden:true}),defineField({name:'status',title:'Estado',type:'string',options:{list:[{title:'Nueva',value:'new'},{title:'Contactada',value:'contacted'},{title:'Cerrada',value:'closed'}]}})],preview:{select:{title:'name',subtitle:'service'}},orderings:[{title:'Más recientes',name:'recent',by:[{field:'createdAt',direction:'desc'}]}]});
export const schemaTypes=[photo,landingPage,inquiry];
