import {getContent,safeUrl} from '@/lib/content';
import {Photo} from '@/components/Photo';
import {ContactForm} from '@/components/ContactForm';
import {FaInstagram,FaFacebookF,FaLinkedinIn,FaWhatsapp,FaGithub,FaTiktok} from 'react-icons/fa';
import {FiLayout,FiGlobe,FiShoppingBag,FiCode,FiArrowUpRight,FiUsers,FiSearch,FiShield} from 'react-icons/fi';
const socialIcons={instagram:FaInstagram,facebook:FaFacebookF,linkedin:FaLinkedinIn,whatsapp:FaWhatsapp,github:FaGithub,tiktok:FaTiktok};
const serviceIcons={landing:FiLayout,web:FiGlobe,shop:FiShoppingBag,code:FiCode};
export default async function Home(){const c=await getContent();const statsIcons=[FiUsers,FiSearch,FiShield];
return <div style={{'--accent':c.appearance.accent,'--card':c.appearance.surface} as React.CSSProperties}>
<a className="skip" href="#main">Saltar al contenido</a>
<header className="header wrap" id="inicio"><a className="brand" href="#inicio" aria-label={c.brand}><Photo photo={c.logo}/></a><nav aria-label="Navegación principal">{c.nav.map(n=><a key={n._key} href={safeUrl(n.href)}>{n.label}</a>)}</nav><a className="button small" href="#contacto">{c.contactLabel}<FiArrowUpRight/></a></header>
<main id="main">
<section className="hero wrap"><div className="hero-copy"><span className="eyebrow">{c.hero.eyebrow}</span><h1>{c.hero.title}</h1><p>{c.hero.description}</p><div className="actions"><a className="button" href="#contacto">{c.hero.primary}<FiArrowUpRight/></a><a className="button outline" href="#proyectos">{c.hero.secondary}</a></div></div><Photo photo={c.hero.image} priority className="portrait"/></section>
{c.sections.map(section=>{switch(section){case 'acerca':return <section key={section} className="about wrap panel" id="acerca"><h2>{c.about.title}</h2><div className="stats">{c.about.stats.map((s,i)=>{const Icon=statsIcons[i%3];return <article key={s._key}><Icon aria-hidden="true"/><h3>{s.title}</h3><strong>{s.subtitle}</strong><p>{s.text}</p></article>})}</div></section>;
case 'proceso':return <section key={section} className="process wrap" id="proceso"><h2>{c.processTitle}</h2><ol>{c.steps.map((s,i)=><li key={s._key}><div><span>{String(i+1).padStart(2,'0')}</span><h3>{s.title}</h3></div><p>{s.text}</p></li>)}</ol></section>;
case 'servicios':return <section key={section} className="services wrap panel" id="servicios"><div className="section-heading"><span>01 /</span><h2>{c.servicesTitle}</h2></div><div className="service-grid">{c.services.map(s=>{const Icon=serviceIcons[s.icon as keyof typeof serviceIcons]||FiCode;return <article key={s._key} className={`service ${s.badge?'featured':''}`}><div className="card-top"><span className="service-icon"><Icon aria-hidden="true"/></span>{s.badge&&<span className="badge">✦ {s.badge}</span>}</div><h3>{s.title}</h3><p className="subtitle">{s.subtitle}</p><p>{s.text}</p><a href="#contacto">{c.serviceCta}<FiArrowUpRight/></a></article>})}</div></section>;
case 'proyectos':return <section key={section} className="projects wrap" id="proyectos"><div className="section-heading"><span>02 /</span><h2>{c.projectsTitle}</h2></div><div className="project-grid">{c.projects.map(p=><article key={p._key} className="project"><div className="project-image"><span className="category">{p.category}</span>{p.image?<Photo photo={p.image}/>:<div className="empty-project"><h3>{p.title}</h3></div>}</div><div className="project-info">{p.image&&<h3>{p.title}</h3>}{p.description&&<p>{p.description}</p>}{p.testimonial&&<blockquote><p>“{p.testimonial}”</p><footer>{p.author}{p.rating&&<span aria-label={`${p.rating} de 5`}> {'★'.repeat(Math.min(5,p.rating))}</span>}</footer></blockquote>}{safeUrl(p.url)&&<a href={safeUrl(p.url)} target="_blank" rel="noopener noreferrer">{c.projectCta}<FiArrowUpRight/></a>}</div></article>)}</div></section>;
case 'contacto':return <section key={section} className="contact wrap" id="contacto"><div className="section-heading"><span>03 /</span><h2>{c.contact.title}</h2></div><p className="contact-intro">{c.contact.description}</p><ContactForm content={c.contact} services={c.services}/></section>;default:return null;}})}
</main><footer className="footer"><div className="wrap footer-grid"><a href="#inicio" className="brand" aria-label={c.brand}><Photo photo={c.logo}/></a><nav aria-label="Navegación del pie">{c.nav.map(n=><a key={n._key} href={safeUrl(n.href)}>{n.label}</a>)}</nav><div className="footer-contact"><h2>{c.footer.title}</h2><a href={`mailto:${c.footer.email}`}>{c.footer.email}</a>{c.footer.phone&&<a href={`tel:${c.footer.phone.replace(/[^+0-9]/g,'')}`}>{c.footer.phone}</a>}<div className="socials">{c.socials.map(s=>{const Icon=socialIcons[s.platform];return safeUrl(s.url)?<a key={s._key} href={safeUrl(s.url)} target="_blank" rel="noopener noreferrer" aria-label={s.platform}><Icon/></a>:null})}</div></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} {c.footer.copyright}</span><div><a href="/privacidad">{c.footer.privacyLabel}</a>{safeUrl(c.footer.claimsUrl)&&<a href={safeUrl(c.footer.claimsUrl)}>{c.footer.claimsLabel}</a>}</div></div></footer></div>;
}

